# Generated by Django 5.0.7 on 2024-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=100)),
                ('description_task', models.CharField(max_length=1000)),
            ],
        ),
    ]
